#!/bin/bash
if [ $1 = "r" ]; then
    sudo rm -R ~/.vim
    sudo rm ~/.vimrc
    sudo rm ~/.gitconfig
    sudo rm ~/.git-completion.bash
    sudo rm ~/.git-prompt.sh
    sudo rm ~/.bash_aliases
    sudo rm ~/.bash_git_settings
    sudo rm ~/.bash_path
    sudo rm ~/.gitignore_global
fi

echo "[Setting up git]"
cp .gitconfig ~
cp .git-completion.bash ~
cp .git-prompt.sh ~

echo "[Setting up vim]"
cp -R .vim ~
cp .vimrc ~
cp -R vim-blade ~/.vim/bundle/vim-blade

if [ ! -d $HOME/.vim/bundle/Vundle.vim ]; then
    git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi

if [ ! -d $HOME/.vimtmp ]; then
    mkdir ~/.vimtmp
fi

cp .bash_aliases ~
cp .bash_git_settings ~
cp .bash_path ~

if [ ! -f $HOME/.jejekule_dotted ]; then
    cat bashrc_setup >> ~/.bashrc
    touch ~/.jejekule_dotted
fi

./solarized_color_setup
vim +PluginInstall +qall
source ~/.bashrc

cp .gitignore_global ~
git config --global core.excludesfile ~/.gitignore_global
